### ISSUE TITLE
Error durring subtitle.parseSync

### ISSUE THREAD

**Issue by FernandoLuizNemeChibli** [gnehs/subtitle-translator#11]
**Context:**
I'm trying to translate a SRT extracted from a MKV file, from English to Portuguese (Brazilian).

**Reproduction:**
- Changed the `config.json` file, with my own `OPENAI_API_KEY` and `"TARGET_LANGUAGE": "PT-BR"`
- Placed the SRT file is at "./src"
- Installed node_modules `npm i`
- Run `node index.js` 

**Error:**
```
/home/fernando/Downloads/subtitle-translator-main/node_modules/subtitle/dist/subtitle.cjs.development.js:109
    return new Error("expected " + expected + " at row " + (index + 1) + ", but received: \"" + row + "\"");
           ^

Error: expected timestamp at row 1, but received: "[Script Info]"
    at Parser.getError (/home/fernando/Downloads/subtitle-translator-main/node_modules/subtitle/dist/subtitle.cjs.development.js:109:12)
    at Parser.parseTimestamp (/home/fernando/Downloads/subtitle-translator-main/node_modules/subtitle/dist/subtitle.cjs.development.js:187:18)
    at Parser.parseId (/home/fernando/Downloads/subtitle-translator-main/node_modules/subtitle/dist/subtitle.cjs.development.js:174:10)
    at Parser.parseHeader (/home/fernando/Downloads/subtitle-translator-main/node_modules/subtitle/dist/subtitle.cjs.development.js:147:14)
    at Parser.parseLine (/home/fernando/Downloads/subtitle-translator-main/node_modules/subtitle/dist/subtitle.cjs.development.js:130:11)
    at /home/fernando/Downloads/subtitle-translator-main/node_modules/subtitle/dist/subtitle.cjs.development.js:299:19
    at Array.forEach (<anonymous>)
    at parseSync (/home/fernando/Downloads/subtitle-translator-main/node_modules/subtitle/dist/subtitle.cjs.development.js:298:44)
    at file:///home/fernando/Downloads/subtitle-translator-main/index.js:17:14
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

**Setup:**
Ubuntu 22.04.2 LTS 
node v16.20.0 (npm v8.19.4)

**Comment by FernandoLuizNemeChibli** [comment]
My SRT wasn't on the right format. Now I'm extracting them using "fluent-ffmpeg" which is working fine.
But now I'm getting the error: 'You exceeded your current quota, please check your plan and billing details.' 
The same as verified at https://github.com/gnehs/subtitle-translator/issues/10#issue-1776090536
